app:
  name: avatar-svc
  image:
    repository: "onecx/onecx-user-profile-avatar-svc"
  db:
    enabled: true
  operator:
    keycloak:
      client:
        enabled: true
        spec:
          kcConfig:
            defaultClientScopes: [ ocx-tn:read ]
    microservice:
      spec:
        description: OneCX User Profile Avatar Backend Service
        name: OneCX User Profile Avatar SVC
