---
openapi: 3.0.3
info:
 title: user-profile-avatar external service
 version: 1.0.0
servers:
 - url: "http://onecx-user-profile-avatar:8080"
tags:
 - name: avatarExternal
paths:
 /v1/avatar/{userId}:
  get:
   tags:
    - avatarExternal
   description: Get Image by id
   operationId: getImage
   parameters:
    - name: userId
      in: path
      required: true
      schema:
       type: string
    - name: refType
      required: true
      in: query
      schema:
       $ref: "#/components/schemas/RefType"
   responses:
    "200":
     description: OK
     content:
      image/*:
       schema:
        minimum: 1
        maximum: 110000
        type: string
        format: binary
 /v1/avatar/me:
  get:
   tags:
    - avatarExternal
   description: Get Image by id
   operationId: getMyImage
   parameters:
    - name: refType
      required: true
      in: query
      schema:
       $ref: "#/components/schemas/RefType"
   responses:
    "200":
     description: OK
     content:
      image/*:
       schema:
        minimum: 1
        maximum: 110000
        type: string
        format: binary
components:
 schemas:
  RefType:
   type: string
   enum: [ small, medium, large ]
   default: 'medium'